import { Button } from '@/components/ui/button'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gray-700">
        <div>
          <Button variant={'secondary'}>Click me</Button>
        </div>
      </main>
    </>
  )
}
